[phases.setup]
nixpkgs = "nixpkgs/nixos-23.11"
providers = ["node"]

[variables]
# Paksa Nixpacks menggunakan Node.js versi 20
NIXPACKS_NODE_VERSION = "20"

[phases.install]
cmds = ["npm ci --ignore-scripts"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "node .next/standalone/server.js"